spring:
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.jdbc.Driver
   druid:
     url: jdbc:mysql://localhost:3306/my_blog
     username: root
     password: root
     initial-size: 10
     max-active: 100
     min-idle: 10
     max-wait: 60000
     pool-prepared-statements: true
     max-pool-prepared-statement-per-connection-size: 20
     time-between-connect-error-millis: 60000
     min-evictable-idle-time-millis: 300000